### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by seancallaway** [NuPass/NuPassWeb#20]
Bring the UI into the 2020s.

Acceptance Criteria:

- [ ] Existing functionality remains in place
- [ ] A newer CSS framework is utilized
- [ ] Page generally looks more appealing

**Comment by Alireza-Sampour** [comment]
I would like to work on this.

**Comment by seancallaway** [comment]
> I would like to work on this.

Go for it. I await your PR.

**Comment by seancallaway** [comment]
Didn't see anything from you, @Alireza-Sampour, so took this myself.
